apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mainlb
  namespace: web3app
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: ac501aef0b5814407914595f55bffd82-37091b6e41589871.elb.eu-north-1.amazonaws.com
      http:
        paths:
          - path: /smart-contract
            pathType: Prefix
            backend:
              service:
                name: smart-contract-service
                port:   
                  number: 8545
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port: 
                  number: 80